spring:
  application:
    name: sat
  config:
    import:
      - "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
resilience4j:
  circuitbreaker:
    instances:
      -align:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      align:
        timeoutDuration: 3s
