spring:
  application:
    name: sat
  config:
    import:
      - "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
resilience4j:
  circuitbreaker:
    instances:
      -align:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20 # 서킷 CLOSE 상태에서 N회 호출 도달 시 failureRateThreshold 실패 비율 계산
        failureRateThreshold: 10 # 실패 10% 이상 시 서킷 오픈
        slowCallDurationThreshold: 2s # 500ms 이상 소요 시 실패로 간주
        slowCallRateThreshold: 50  # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
        minimumNumberOfCalls: 10  # 집계에 필요한 최소 호출 수
        waitDurationInOpenState: 30000   # OPEN -> HALF-OPEN 전환 전 기다리는 시간
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    wait-duration: 100   # 재시도 사이 간격
    max-attempts: 2   # 재시도 횟수(최초 호출 포함)
  timelimiter:
    instances:
      align:
        timeoutDuration: 3s
