spring:
  application:
    name: sat
  data:
    mongodb:
      uri: mongodb+srv://sat:qwer@sat.4gmfwlp.mongodb.net/sat?retryWrites=true
sat:
  data:
    prefix: /Users/ampersandor/data/sat/
  config:
    import:
      - "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh